version: '3.8'
services:
  simulation:
    build: ./simulation
    container_name: simulation
    ports:
      - "8001:8001"

  backend:
    build: ./dashboard/backend
    container_name: backend
    environment:
      - SIM_URL=ws://simulation:8001/ws
    ports:
      - "8000:8000"

# docker compose up --build
# Browse to http://localhost:8000 for the dashboard UI.
